---
- name: Начинаем работу с Ansible
  hosts: all
  become: yes #Все команды от имени root
  tasks:
  - name: "Установка по и dockera"
    block:
      - name: Настройка по
        apt:
          name:
            - apt-transport-https # http -> https
            - ca-certificates # набор сертификатов 
            - curl # скачивает файлы
            - gnupg # Программа, работает с цифровыми подписями и шифрованием
            - lsb-release # Утилита ,которая сообщает системе ее имя далее
            - unzip # Для sqlite.zip
          state: present # проверяет установлен ли пакет / устанавливает
          update_cache: yes # apt update

      - name: Прописали GPG-ключ docker 
        apt_key:
          url: https://download.docker.com/linux/debian/gpg
          state: present
          #apt_key цифровая подпись 

      - name: Настройка репозитория docker
        apt_repository:
          repo: "deb [arch=amd64] https://download.docker.com/linux/debian {{ ansible_distribution_release }} stable"
          state: present
          # ansible_distributor_release сам определит какая у нас ос 
          # через зеркало не хотело грузить , но загрузило через официальную ссылку (хотя прокси нет)

      - name: Установка docker
        apt:
          name:
            - docker-ce
            - docker-ce-cli
            - containerd.io
          state: present
          update_cache: yes

      - name: Запуск docker
        systemd:
          name: docker
          enabled: yes
          state: started
    tags: install_docker
    # 7 Задание

  - name: "Работа с Sqlite"
    block:
      - name: "Скачивание архива SQLite"
      #Пришлось сделать через wget и браузер , т.к у нас загружается html страница с сайта , вместо архива
        shell: |
          wget -U "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36" \
          https://www.sqlite.org/2018/sqlite-amalgamation-3260000.zip \
          -O /home/vagrant/project/sqlite.zip
        args:
          creates: /home/vagrant/project/sqlite.zip

      - name: "Распаковка архива SQLite"
        unarchive:
          src: "/home/vagrant/project/sqlite.zip"
          dest: "/home/vagrant/project/"
          remote_src: yes
          extra_opts: ['-j'] # Извлекает файлы без создания вложенной папки
          creates: "/home/vagrant/project/sqlite3.c"

      - name: "Собираем наш docker образ"
        shell: |
          if [ -z "$(docker images -q sqlite-builder:latest)" ]; then
          docker build -t sqlite-builder /home/vagrant/project
          fi
        # проверяем наличие докер образа , флаг -q , покажет id образа , если он есть
        # и -z проверяет на zero т.е если в скобочках будет пусто , тогда docker 
        # строит образ , сделал , чтобы постоянно не создавать новый образ . 

      - name: "Запускаем docker образ"
        shell: |
          docker run --rm -v /home/vagrant/project:/app sqlite-builder sh -c "
          mkdir -p build && cd build && \
          cmake .. && \
          make > build_log.txt 2>&1"
        args:
          chdir: "/home/vagrant/project"
          creates: "/home/vagrant/project/build/libsqlite3.so"

      - name: "Проверка создания so файла"
        stat:
          path: "/home/vagrant/project/build/libsqlite3.so"
        register: build_status

      - name: "Результат"
        debug:
          msg: "Библиотека libsqlite3.so и лог сборки готовы в папке build/"
        when: build_status.stat.exists
    tags: Sqlite
  # 8 задание
  - name: "Работа с Conan"
    block:
      - name: "Установка python и pip"
        apt:
          name: [python3-pip, python3-setuptools, python3-venv]
          state: present
      
      #pip менеджер пакетов для python
      - name: "Установка conan через pip"
        pip:
          name: conan
          state: present

      - name: "Определение комплиятора для conan"
        shell: "conan profile detect"
        become_user: vagrant # Профиль должен быть user , а не root
        args:
          creates: "/home/vagrant/.conan2/profiles/default"
      
      #Здесь DCMAKE_TOOLCHAIN_FILE = conan_toolchain.cmake т.е conan и cmake связываются
      #--build=missing если нет библиотеки под наш комплиятор , conan его скачивает
      - name: "Сборка проекта C++ через conan и cmake"
        shell: |
          conan install . --output-folder=build_conan --build=missing
          cd build_conan
          cmake .. \
            -DCMAKE_TOOLCHAIN_FILE=build/Release/generators/conan_toolchain.cmake \
            -DCMAKE_BUILD_TYPE=Release
          cmake --build . 
        args:
          chdir: "/home/vagrant/project/task8"
          # Чтобы не пересобирать, если файл уже есть
          creates: "/home/vagrant/project/task8/build_conan/test_conan"
        become_user: vagrant

      - name: "Проверка: запуск скомпилированной программы"
        shell: "./build_conan/test_conan"
        args:
          chdir: "/home/vagrant/project/task8"
        register: conan_result

      - name: "Вывод результата работы программы"
        debug:
          msg: "{{ conan_result.stdout }}"
    tags: "Conan"